version: '3.8'

services:
  nginx-loadbalancer:
    image: nginx
    container_name: nginx-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web_server_1
      - web_server_2
    networks:
      - webnet

  web_server_1:
    image: nginx
    container_name: web_server_1
    ports:
      - "8081:80"
    volumes:
      - ./web1-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

  web_server_1_exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: web_server_1_exporter
    ports:
      - "9114:9113"
    command: -nginx.scrape-uri=http://web_server_1/nginx_status
    depends_on:
      - web_server_1
    networks:
      - webnet

  web_server_2:
    image: nginx
    container_name: web_server_2
    ports:
      - "8082:80"
    volumes:
      - ./web2-nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

  web_server_2_exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: web_server_2_exporter
    ports:
      - "9115:9113"
    command: -nginx.scrape-uri=http://web_server_2/nginx_status
    depends_on:
      - web_server_2
    networks:
      - webnet


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - nginx-loadbalancer
    networks:
      - webnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - webnet

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.11.0
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command: -nginx.scrape-uri=http://nginx-loadbalancer/nginx_status
    depends_on:
      - nginx-loadbalancer
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
