global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'web_servers'
    static_configs:
      - targets:
          - 'web_server_1_exporter:9113'
          - 'web_server_2_exporter:9113'
